name: CI

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - 2.7.5
          - 3.0.3
          - 3.1.4
          - 3.2.3
          - '3.3'
          - '3.4'
          - head
        # TODO: Add jruby
        include:
          - os: windows-latest
            ruby: 2.7.5
          - os: macos-latest
            ruby: 2.7.5


    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rake spec
